OpenMP support for TRD tracking
davidrohr/AliTPCCommon pull request #1
Opened 2018-12-07 14:06 UTC by martenole

Hi David, I have some changes to the TRD tracking that I would like to push, but there are conflicts with your master branch. Can we still merge them?
OpenMP works fine now. I still have to check the transformation matrices from the new flat geometry.
Cheers,
Ole

2018-12-09 12:47 UTC, davidrohr requested changes
Hi @martenole : I think in general it is fine, I left some minor comments inline.
But please do not use git merge, but rebase your branch onto the master for the pull request.

2018-12-09 12:47 UTC, davidrohr commented on TPCCAGPUTracking/CMakeLists.txt
> +    target_link_libraries(${MODULE} OpenMP::OpenMP_CXX)
we cannot change the AliRoot cmake here, you can have this change only locally, but not push it.
In order not to break AliRoot, please also add an
`#ifdef HLTCA_HAVE_OPENMP`
before all omp pragmas and omp_ API calls.

2018-12-09 12:47 UTC, davidrohr commented on TPCCAGPUTracking/GlobalTracker/AliGPUReconstruction.cxx
> +		if (trk.Looper()) continue;
OK for now, should be cleaned up later in the TPC code.

2018-12-09 12:47 UTC, davidrohr commented on TPCCAGPUTracking/GlobalTracker/AliGPUReconstruction.h
> +    if (runConstructor)
please fix the indentation

2018-12-09 12:47 UTC, davidrohr commented on TPCCAGPUTracking/TRDTracking/AliHLTTRDTracker.cxx
> -    if (!fExternalGeometry) delete fGeo;
I think we have to keep the destructor for debug at keast

2018-12-09 12:47 UTC, davidrohr commented on TPCCAGPUTracking/TRDTracking/AliHLTTRDTrackerComponent.cxx
> +  fGeo = new AliHLTTRDGeometry();
You could put the other checks here, if the AliGeometry for TRD is actually available, which were with the Geometry initialization before.

2018-12-10 15:17 UTC, martenole commented
I have applied the requested changes and will open another pull request with the current code.

2018-12-10 15:17 UTC, closed without merging